ALTER TABLE "Store" ADD COLUMN "deliveryPerKmTiyn" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Store" ADD COLUMN "freeDeliveryAboveTiyn" INTEGER;
ALTER TABLE "Store" ADD COLUMN "deliveryRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 15;
